# Generated by Django 4.1.5 on 2023-03-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0002_dashboard_latest_lecture_usergrowths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="homework_progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
