# Generated by Django 4.1.5 on 2023-03-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0006_remove_dashboard_homework_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="attendance",
            field=models.CharField(default="", max_length=50),
        ),
    ]
