# Generated by Django 4.1.5 on 2023-03-06 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code=400,
                        message="Enter a valid phone number.",
                        regex="^010([0-9]{4})([0-9]{4})$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="secret_key",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
