# Generated by Django 4.1.5 on 2023-03-30 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code=400,
                        message="Enter a valid phone number.",
                        regex="^010([0-9]{4})([0-9]{4})$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="secret_key",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
