# Generated by Django 4.1.5 on 2023-03-04 06:11

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecretKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("master", models.CharField(max_length=50, unique=True)),
                ("phone", phone_field.models.PhoneField(max_length=31)),
                ("secret_key", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
