# Generated by Django 4.1.5 on 2023-03-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretkeys", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secretkey",
            old_name="secret_key",
            new_name="key",
        ),
        migrations.AddField(
            model_name="secretkey",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
