# Generated by Django 4.1.5 on 2023-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secretkeys", "0003_alter_secretkey_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secretkey",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="secretkey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
