# Generated by Django 4.1.5 on 2023-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursereview",
            name="score",
            field=models.PositiveIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
    ]
