# Generated by Django 4.1.5 on 2023-03-16 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lecture_comments", "0002_lecturecomment_lecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreply",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="lecture_comments.lecturecomment",
            ),
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
