# Generated by Django 4.1.5 on 2023-03-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture_comments", "0003_alter_commentreply_comment_alter_commentreply_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreply",
            name="reply",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="lecturecomment",
            name="comment",
            field=models.TextField(max_length=1000),
        ),
    ]
