# Generated by Django 4.1.5 on 2023-03-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture_comments", "0004_alter_commentreply_reply_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentreply",
            old_name="comment",
            new_name="lecture_comment",
        ),
        migrations.AlterField(
            model_name="commentreply",
            name="reply",
            field=models.CharField(max_length=255),
        ),
    ]
