# Generated by Django 4.1.5 on 2023-03-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=10)),
                ("teacher", models.CharField(max_length=20)),
                ("duration", models.PositiveIntegerField()),
                ("videoId", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
