# Generated by Django 4.1.5 on 2023-03-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LectureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("teacher", models.CharField(max_length=20)),
                ("duration", models.PositiveIntegerField()),
                ("videoId", models.CharField(max_length=100)),
                (
                    "date",
                    models.CharField(
                        blank=True, help_text="yyyymmdd", max_length=8, null=True
                    ),
                ),
                ("today_lecture", models.BooleanField(default=False)),
                ("active_lecture", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.lecturecategory",
                    ),
                ),
            ],
        ),
    ]
