# Generated by Django 4.1.5 on 2023-03-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_alter_lectures_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectures",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
