# Generated by Django 4.1.5 on 2023-03-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_alter_lectures_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectures",
            name="date",
            field=models.CharField(
                blank=True, help_text="yyyymmdd", max_length=8, null=True
            ),
        ),
    ]
