# Generated by Django 4.1.5 on 2023-03-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0005_rename_lectures_lecture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecture",
            old_name="active",
            new_name="today_lecture",
        ),
    ]
