# Generated by Django 4.1.5 on 2023-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0006_rename_active_lecture_today_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="active_lecture",
            field=models.BooleanField(default=False),
        ),
    ]
