# Generated by Django 4.1.5 on 2023-03-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture_rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lectureroom",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
