# Generated by Django 4.1.5 on 2023-03-13 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_alter_dashboard_homework_progress"),
        ("homeworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_submitted", models.BooleanField(default=False)),
                ("url", models.CharField(blank=True, max_length=100, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboards.dashboard",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homeworks.homework",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
