# Generated by Django 4.1.5 on 2023-03-19 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0004_alter_storage_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="homeworks.homework",
            ),
        ),
    ]
