# Generated by Django 4.1.5 on 2023-03-19 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0005_remove_dashboard_latest_lecture"),
        ("homeworks", "0005_alter_submission_homework"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submission",
                to="dashboards.dashboard",
            ),
        ),
    ]
