# Generated by Django 4.1.5 on 2023-03-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0006_alter_submission_dashboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
