# Generated by Django 4.1.5 on 2023-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0007_alter_storage_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="url",
            field=models.TextField(),
        ),
    ]
